services:

  geoserver:
    image: ghcr.io/biodiversitydata-se/geoserver:1.0.1
    #image: sbdi/geoserver-dev
    #build:
    #  context: ../geoserver
    env_file: ./docker/.env
    environment:
      JAVA_OPTS: -Xmx2g -Xms128m -Xss512k -Djava.awt.headless=true
      TZ: Europe/Stockholm
    volumes:
      - /data/geoserver_data_dir:/data/geoserver_data_dir
      - /data/spatial-data:/data/spatial-data
    ports:
      - "8079:8080"

  postgis:
    image: postgis/postgis:13-3.4
    env_file: ./docker/.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      TZ: Europe/Stockholm
    ports:
      - "5432:5432"
    volumes:
      - db_data_spatial-service:/var/lib/postgresql/data
      - ./docker/postgres/init_layersdb.sql:/docker-entrypoint-initdb.d/init_layersdb.sql

  spatial-service:
    image: sbdi/spatial-service-dev
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./sbdi/data/config/spatial-service-config.yml:/data/spatial-service/config/spatial-service-config.yml

volumes:
  db_data_spatial-service:
